# Generated by Django 3.0.1 on 2020-01-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200104_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='statue',
            new_name='status',
        ),
    ]
